name: Harttle Land
url: http://harttle.com
description: Keep it simple, stupid.
keywords: 
  - Web
  - HTML
  - CSS
  - JavaScript
  - C++
  - Linux
  - Bash
  - Vim

permalink: /:year/:month/:day/:title.html
paginate: 4
paginate_path: "page:num"

markdown: kramdown
markdown_ext:  md
excerpt_separator: "<!--more-->"

exclude: ['README.md', '.*', 'scripts/', 'bak', 'Gemfile']

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed

