title: Chuang Peng
description: 彭创，一名Web前端开发者 | 爱分享互联网技术 | 共享前端博客开放平台
url: http://searchuang.com
author: 彭创 | Chuang Peng
logo: assets/img/favicon.png
keywords: 
  - 彭创
  - searchuang
  - 博客
  - Web
  - HTML
  - CSS
  - HTML5
  - CSS3
  - JavaScript
  - C++
  - Linux
  - Bash
  - Vim
  - Node
  - React
  - Vue
  - 微信小程序
  - Webpack

permalink: /:year/:month/:day/:title.html
paginate: 7
paginate_path: "page:num"
markdown: kramdown
markdown_ext:  md
excerpt_separator: "<!--more-->"
highlighter: rouge
lsi: false
exclude: ['README.md', '.*', 'bin/', 'Gemfile', 'node_modules', '*.log', 'package.json']
kramdown:
  input: GFM
  hard_wrap: false

ga: 'UA-110608730-1'
disqus: 'searchuang'

sass:
    style: compressed

collections:
  effective-cpp:
    output: true
    permalink: /:year/:month/:day/:title.html
  git-workflow:
    output: true
    permalink: /:year/:month/:day/:title.html
  vim-practice:
    output: true
    permalink: /:year/:month/:day/:title.html

defaults:
  -
    scope:
      path: "_drafts"
    values:
      layout: "blog"
  -
    scope:
      path: "_posts"
    values:
      layout: "blog"
  -
    scope:
      path: "_effective-cpp"
    values:
      layout: "blog"
  -
    scope:
      path: "_git-workflow"
    values:
      layout: "blog"
  -
    scope:
      path: "_vim-practice"
    values:
      layout: "blog"

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate

whitelist:
  - jekyll-redirect-from
