title: Chuang Peng
description: 彭创，一名Web前端开发者 | 爱分享互联网技术 | 共享前端博客开放平台
url: https://cp9266.github.io
author: Chuang Peng
email: cp9266@gmailcom
logo: assets/img/favicon.png
keywords: 
  - 彭创
  - cp9266
  - 博客
  - Web
  - HTML
  - CSS
  - HTML5
  - CSS3
  - JavaScript
  - C++
  - Linux
  - Bash
  - Vim
  - Node
  - React
  - Vue
  - 微信小程序
  - Webpack

permalink: /:year/:month/:day/:title.html
paginate: 7
paginate_path: "page:num"
markdown: kramdown
markdown_ext: md
excerpt_separator: "<!--more-->"
highlighter: rouge
lsi: false
exclude: ['README.md', '.*', 'bin/', 'Gemfile', 'node_modules', '*.log', 'package.json', 'vendor']
kramdown:
  input: GFM
  hard_wrap: false

ga: 'UA-110608730-1'

sass:
    style: compressed

defaults:
  -
    scope:
      path: "_drafts"
    values:
      layout: "blog"
  -
    scope:
      path: "_posts"
    values:
      layout: "blog"

series:
  'Effective-C++': '/effective-cpp.html'
  'Vim-Practice': '/vim-practice.html'
  'Git-Workflow': '/git-workflow.html'

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-include-cache
